gui:
  spinner:
    frames: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']
    rate: 100
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
  autoForwardBranches: none
os:
  editPreset: 'nvim'
